import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Камеры</title>
        <meta name="cameras" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Добро пожаловать в интернет магазин!</p>
          <div>
            <Link href="/cameras">
              Перейти в каталог
              <Image
                src="/catalog.png"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={50}
                height={50}
                priority
              />
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
